spring:
  profiles:
    active: dev
    include: common

---

spring:
  config:
    activate:
      on-profile: dev

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
        dialect: org.hibernate.dialect.MySQLDialect

  datasource:
    url: jdbc:mysql://${MYSQL_HOST}/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
