
spring:
  config:
    activate:
      on-profile: prod

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
        dialect: org.hibernate.dialect.MySQLDialect

  datasource:
    url: jdbc:mysql://${MYSQL_HOST}/prod?useSSL=false&allowPublicKeyRetrieval=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
