spring:
  application:
    name: tracker

  # Swagger UI Configuration
  doc:
    swagger-ui:
      path: /swagger-ui.html
    api-docs:
      path: /api-docs

  # Load Secret Properties
  config:
    import: optional:file:.env[.properties]

  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ""

  sql:
    init:
      data-locations: classpath:data.sql
      mode: always 