name: 개발서버 CD

on:
  workflow_dispatch:
  push:
    branches: develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build project using Gradle
        run: ./gradlew clean bootJar

      - name: Upload build artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: tracker-develop-jar
          path: build/libs/tracker-0.0.1-SNAPSHOT.jar

  deploy:
    runs-on: [self-hosted, dev]
    needs: build

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: tracker-develop-jar
          path: .

      - name: Check if server is running on port 8080
        id: check-server-on-port
        run: |
          echo "Checking if port 8080 is in use..."
          PID=$(lsof -t -i:8080 || true)
          if [ -n "$PID" ]; then
            echo "server_running=true" >> $GITHUB_ENV
            echo "PID=$PID" >> $GITHUB_ENV
          else
            echo "server_running=false" >> $GITHUB_ENV
          fi
      - name: Stop server if running
        if: env.server_running == 'true'
        run: |
          echo "Stopping server running on port 8080..."
          kill -9 $PID
          echo "Preivous running Server stopped."
      - name: Start server
        env:
          RUNNER_TRACKING_ID: ""
        run: |
          sudo nohup java -jar tracker-0.0.1-SNAPSHOT.jar &
          echo "Lastest Backend API Server started."
