name: PM - Issue 자동 관리

on:
  issues:
    types: assigned

jobs:
  create-issue-branch:
    name: "이슈 할당 -> 브랜치 & Draft PR 자동 생성"
    runs-on: ubuntu-latest
    steps:
      - name: create the issue branch
        uses: robvanderleek/create-issue-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
